# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/File/NTHU/2A/verilog/G14_Final_project/G14_Final_project.srcs/sources_1/ip/blk_mem_gen_17/blk_mem_gen_17.xci
# IP: The module: 'blk_mem_gen_17' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/File/NTHU/2A/verilog/G14_Final_project/G14_Final_project.gen/sources_1/ip/blk_mem_gen_17/blk_mem_gen_17_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_17'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/File/NTHU/2A/verilog/G14_Final_project/G14_Final_project.srcs/sources_1/ip/blk_mem_gen_17/blk_mem_gen_17.xci
# IP: The module: 'blk_mem_gen_17' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/File/NTHU/2A/verilog/G14_Final_project/G14_Final_project.gen/sources_1/ip/blk_mem_gen_17/blk_mem_gen_17_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_17'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
